contents:
  keyring:
    - https://packages.wolfi.dev/os/wolfi-signing.rsa.pub
  repositories:
    - https://packages.wolfi.dev/os
  packages:
    - wolfi-baselayout
    - busybox
    - kustomize
    - docker
    - python-3
    - py3-pip
    - openjdk-11
    - glibc-locale-en
    - libstdc++
    - gradle-8
    - openjdk-11-default-jvm
    - maven
    - jq
    - git
    - ca-certificates-bundle

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

entrypoint:
  command: /usr/bin/sh

archs:
  - amd64  