FROM cgr.dev/chainguard/tomcat

RUN rm -rf /usr/local/tomcat/webapps/ROOT
RUN rm -rf /usr/local/tomcat/webapps/docs
RUN rm -rf /usr/local/tomcat/webapps/examples
RUN rm -rf /usr/local/tomcat/webapps/manager
RUN rm -rf /usr/local/tomcat/webapps/host-manager

# Change directory to Tomcat webapps folder and download the latest Castle Mock war file
WORKDIR  /usr/local/tomcat/webapps 

COPY castlemock.war .
# Expose HTTP port 8080
EXPOSE 8080