name: Notify Discord on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Load user photo URL
      id: load_photo
      run: |
        PHOTO_URL=$(jq -r --arg user "${{ github.actor }}" '.[$user]' .github/user_photos.json)
        echo "PHOTO_URL=$PHOTO_URL" >> $GITHUB_ENV
        echo "Loaded photo URL: $PHOTO_URL"
        
    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        PHOTO_URL: ${{ env.PHOTO_URL }}
      run: |
        COMMIT_INFO=$(git log -1 --pretty=format:"%H - %an: %s")
        MOTIVATIONAL_MESSAGE="🚀 Fantastic work, $GITHUB_ACTOR! 🚀  You've just pushed another commit: \`\`\` $COMMIT_INFO \`\`\`   Your dedication is really making a difference!  🌟 Keep the momentum going and let's push even harder.  Our deadline on **6/6** is fast approaching, and with your continuous efforts, we're sure to achieve our goals!   **Let's crush this together! 💪**"
        PAYLOAD=$(jq -n --arg content "New push to branch \`${{ github.ref_name }}\`: $MOTIVATIONAL_MESSAGE" \
                      --arg image_url "$PHOTO_URL" \
                      '{username: "Git Bot", content: $content, embeds: [{image: {url: $image_url}}]}')
        curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK_URL