name: Notify Discord on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Load user photo URL
      id: load_photo
      run: |
        PHOTO_URL=$(jq -r --arg user "${{ github.actor }}" '.[$user]' .github/user_photos.json)
        echo "::set-output name=photo_url::$PHOTO_URL"

    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
      run: |
        COMMIT_INFO=$(git log -1 --pretty=format:"%H - %an: %s")
        MOTIVATIONAL_MESSAGE="Great job, $GITHUB_ACTOR! Keep up the excellent work and keep those commits coming! Remember, our deadline is on 6/6. Let's make it happen!"
        PAYLOAD=$(jq -n --arg content "New push to branch \`${{ github.ref_name }}\`:\n\`\`\`$COMMIT_INFO\`\`\`\n\n$MOTIVATIONAL_MESSAGE" \
                      --arg avatar_url "${{ steps.load_photo.outputs.photo_url }}" \
                      '{username: "Git Bot", content: $content, avatar_url: $avatar_url}')
        curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
