name: Notify Discord on Push

on: [push]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install jq
      run: sudo apt-get install -y jq

    - name: Load user photo URL
      id: load_photo
      run: |
        PHOTO_URL=$(jq -r --arg user "${{ github.actor }}" '.[$user]' .github/user_photos.json)
        echo "PHOTO_URL=$PHOTO_URL" >> $GITHUB_ENV
        echo "Loaded photo URL: $PHOTO_URL"

    - name: Send notification to Discord
      env:
        DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
        GITHUB_ACTOR: ${{ github.actor }}
        PHOTO_URL: ${{ env.PHOTO_URL }}
      run: |
        SHORT_COMMIT=$(git rev-parse --short HEAD)
        COMMIT_INFO=$(git log -1 --pretty=format:"%h - %an: %s")
        MESSAGES=("🚀 Fantastic work, $GITHUB_ACTOR! 🚀  You've just pushed another commit: \`\`\` $SHORT_COMMIT \`\`\`   Your dedication is really making a difference!  🌟 Keep the momentum going and let's push even harder.  Our deadline on **6/6** is fast approaching, and with your continuous efforts, we're sure to achieve our goals!   **Let's crush this together! 💪**  Check the latest updates on [our website](https://khoyout.live/)."
                  "💥 Amazing job, $GITHUB_ACTOR! 💥 Another commit pushed: \`\`\` $SHORT_COMMIT \`\`\` Your hard work is paying off! 🌟 Stay focused and let's keep pushing. The deadline on **6/6** is just around the corner. Together, we can do this! **Keep it up! 🔥**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🌟 Excellent work, $GITHUB_ACTOR! 🌟 You've committed: \`\`\` $SHORT_COMMIT \`\`\` Your effort is truly inspiring! Let's continue this momentum and achieve our goals by **6/6**. **You're doing great! 💪**  Check the latest updates on [our website](https://khoyout.live/)."
                  "✨ Awesome job, $GITHUB_ACTOR! ✨ New commit: \`\`\` $SHORT_COMMIT \`\`\` Your contributions are invaluable! Let's maintain this pace and aim for our deadline on **6/6**. **Keep shining! 🌟**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🔥 Incredible work, $GITHUB_ACTOR! 🔥 You've added: \`\`\` $SHORT_COMMIT \`\`\` Your dedication is impressive! Let's keep this up and hit our deadline on **6/6**. **Together, we're unstoppable! 💪**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🎉 Great job, $GITHUB_ACTOR! 🎉 Another commit in the books: \`\`\` $SHORT_COMMIT \`\`\` Your commitment is driving us forward! Let's push even harder and reach our goals by **6/6**. **We got this! 🚀**  Check the latest updates on [our website](https://khoyout.live/)."
                  "👏 Fantastic effort, $GITHUB_ACTOR! 👏 New commit pushed: \`\`\` $SHORT_COMMIT \`\`\` Your hard work is making a huge impact! Let's continue this drive and meet our deadline on **6/6**. **Keep going strong! 💪**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🌠 Stellar work, $GITHUB_ACTOR! 🌠 Committed: \`\`\` $SHORT_COMMIT \`\`\` Your dedication is shining through! Let's keep the momentum and reach our goals by **6/6**. **You rock! 🤘**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🚀 Superb job, $GITHUB_ACTOR! 🚀 You've pushed: \`\`\` $SHORT_COMMIT \`\`\` Your efforts are pushing us forward! Let's stay focused and achieve our targets by **6/6**. **Keep it up, champ! 💪**  Check the latest updates on [our website](https://khoyout.live/)."
                  "🎯 Excellent effort, $GITHUB_ACTOR! 🎯 New commit: \`\`\` $SHORT_COMMIT \`\`\` Your dedication is truly appreciated! Let's keep pushing towards our deadline on **6/6**. **Together, we can do it! 🚀**  Check the latest updates on [our website](https://khoyout.live/).")
        RANDOM_INDEX=$((RANDOM % ${#MESSAGES[@]}))
        MOTIVATIONAL_MESSAGE=${MESSAGES[$RANDOM_INDEX]}
        PAYLOAD=$(jq -n --arg content "New push to branch \`${{ github.ref_name }}\`: $MOTIVATIONAL_MESSAGE" \
                      --arg image_url "$PHOTO_URL" \
                      '{username: "Git Bot", content: $content, embeds: [{image: {url: $image_url}}]}')
        curl -H "Content-Type: application/json" -X POST -d "$PAYLOAD" $DISCORD_WEBHOOK_URL
