contents:
  packages:
    - katib-suggestion-goptuna-compat

accounts:
  groups:
    - groupname: nonroot
      gid: 65532
  users:
    - username: nonroot
      uid: 65532
      gid: 65532
  run-as: 65532

work-dir: /opt/katib

entrypoint:
  command: ./katib-suggestion-goptuna
